package pl.dekrate.kofeino.common.domain.model

/**
 * The canonical shared domain model for a single caffeine intake entry.
 *
 * This is a pure Kotlin data class (no Room or Android dependencies) used
 * across both `:app` and `:wear` modules.  It mirrors the fields of the
 * per-module `@Entity` classes so that data can be exchanged between
 * devices without coupling to either platform's database layer.
 *
 * @property id                    Unique identifier (auto-generated by the database).
 * @property drinkId               Optional foreign key referencing a [DrinkEntity].
 * @property drinkName             Human-readable name of the drink (e.g. "Coffee").
 * @property caffeineMg            Total caffeine content in milligrams.
 * @property volumeMl              Volume of the drink in millilitres.
 * @property timestamp             Epoch millis when the intake was recorded.
 * @property lastModifiedTimestamp Epoch millis of the last modification.
 * @property sourceDeviceId        Identifier of the device that created this entry.
 */
data class CaffeineIntake(
    val id: Long = 0,
    val drinkId: Long? = null,
    val drinkName: String,
    val caffeineMg: Int,
    val volumeMl: Int,
    val timestamp: Long,
    val lastModifiedTimestamp: Long = 0L,
    val sourceDeviceId: String = "",
)
