package pl.dekrate.kofeino.common.domain.model

/**
 * The canonical shared domain model for a saved drink definition.
 *
 * This is a pure Kotlin data class (no Room or Android dependencies) used
 * across both `:app` and `:wear` modules.  It mirrors the fields of the
 * per-module `@Entity` classes so that drinks can be synchronised between
 * devices without coupling to either platform's database layer.
 *
 * @property id                    Unique identifier (auto-generated by the database).
 * @property name                  Human-readable drink name.
 * @property caffeineMg            Total caffeine content in milligrams.
 * @property volumeMl              Volume of the drink in millilitres.
 * @property isDefault             Whether this is a built-in default drink.
 * @property lastModifiedTimestamp Epoch millis of the last modification.
 * @property sourceDeviceId        Identifier of the device that created this entry.
 */
data class DrinkEntity(
    val id: Long = 0,
    val name: String,
    val caffeineMg: Int,
    val volumeMl: Int,
    val isDefault: Boolean = false,
    val lastModifiedTimestamp: Long = 0L,
    val sourceDeviceId: String = "",
)
